CREATE TABLE t_user(
  id INT AUTO_INCREMENT,
  user_name VARCHAR(10) DEFAULT NULL ,
  password VARCHAR(10) DEFAULT NULL ,
  true_name VARCHAR(10) DEFAULT NULL ,
  addr VARCHAR(20) DEFAULT NULL ,
  phone VARCHAR(20) DEFAULT NULL ,
  PRIMARY KEY (id)
);